import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to the main page</h1>

        <ul>
          <li>
            <Link href="/index">
              <code>/index</code>
            </Link>
          </li>
          <li>
            <Link href="/articles">
              <code>/articles</code>
            </Link>
          </li>
          <li>
            <Link href="/articles/index">
              <code>/articles/index</code>
            </Link>
          </li>
        </ul>
      </main>
    </>
  )
}
